#=====================================================================================
# Description:   Build OpenWrt with Image Builder
# Instructions:  https://openwrt.org/docs/guide-user/additional-software/imagebuilder
#                https://github.com/ophub/amlogic-s9xxx-openwrt
# Download from: https://downloads.openwrt.org/releases
#                https://downloads.immortalwrt.org/releases
#=====================================================================================

name: Generate friWrt Amlogic Firmware

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: "Select the release branch:"
        required: true
        default: "openwrt:23.05.2"
        type: choice
        options:
          - openwrt:21.02.7
          - openwrt:23.05.2
          - immortalwrt:21.02.7
          - immortalwrt:23.05.1
      openwrt_board:
        description: "Select device board"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - s905w_s905x_s905mb_s905l3b_s905x2_s905x3_s912_s922x_s922x-ct2000_s922x-reva
          - s905x3-x88-pro-x3_s912-m8s-pro_s905x-t95_s912-t95z-plus_s905l3-unt400g1_s905lb-r3300l
          - seewo-sv21_smart-am40_station-m1_sw799_tn3399_zysj_tvi3315a_xiaobao_zcube1-max
          - vplus_tanix-tx6_tqc-a01
          - a311d
          - beikeyun
          - chainedbox
          - crrc
          - dg3399
          - dlfr100
          - e25
          - eaidk-610
          - emb3531
          - fine3399
          - firefly-rk3399
          - jp-tvbox
          - h28k
          - h66k
          - h68k
          - h69k
          - h88k
          - h88k-v3
          - hugsun-x99
          - ipc-r
          - king3399
          - kylin3399
          - leez
          - lx-r3s
          - nanopi-r5c
          - nanopi-r5s
          - panther-x2
          - r66s
          - r68s
          - renegade-rk3328
          - rk3318-box
          - rock5b
          - s905
          - s905-beelink-mini
          - s905-mxqpro-plus
          - s905d
          - s905d-ki-pro
          - s905d-sml5442tw
          - s905l
          - s905l-mg101
          - s905l2
          - s905l2-e900v21e
          - s905l2-wojia
          - s905l3
          - s905l3-cm211
          - s905l3-unt400g1
          - s905l3a
          - s905l3a-cm311
          - s905l3a-m401a
          - s905l3b
          - s905l3b-e900v22d
          - s905l3b-e900v22e
          - s905l3b-ip103h
          - s905l3b-rg020et-ca
          - s905l3b-unt403a
          - s905lb-q96-mini
          - s905lb-r3300l
          - s905mb
          - s905w
          - s905w-w95
          - s905w-x96-mini
          - s905w-x96w
          - s905x
          - s905x-b860h
          - s905x-nexbox-a95x
          - s905x-t95
          - s905x-tbee
          - s905x-tx9
          - s905x2
          - s905x2-km3
          - s905x2-x96max-2g
          - s905x3
          - s905x3-2101
          - s905x3-a100
          - s905x3-a95xf3
          - s905x3-a95xf3-gb
          - s905x3-b
          - s905x3-h96max
          - s905x3-hk1
          - s905x3-ip1001m
          - s905x3-q1
          - s905x3-q2
          - s905x3-tx3
          - s905x3-tx3-bz
          - s905x3-ugoosx3
          - s905x3-whale
          - s905x3-x88-pro-x3
          - s905x3-x96air
          - s905x3-x96air-gb
          - s905x3-x96max
          - s912
          - s912-h96pro-plus
          - s912-m8s-pro
          - s912-nexbox-a1
          - s912-nexbox-a2
          - s912-phicomm-t1
          - s912-t95z-plus
          - s912-tx8-max
          - s912-tx9-pro-2g
          - s912-tx9-pro-3g
          - s912-x92
          - s912-zyxq-fake
          - s922x
          - s922x-ct2000
          - s922x-gtking
          - s922x-gtkingpro-h
          - s922x-odroid-n2
          - s922x-reva
          - s922x-ugoos-am6
          - seewo-sv21
          - smart-am40
          - station-m1
          - sw799
          - tanix-tx6
          - tn3399
          - tqc-a01
          - tvi3315a
          - vplus
          - xiaobao
          - zcube1-max
          - zysj
      openwrt_kernel:
        description: "Select kernel version"
        required: false
        default: "5.15.1_6.1.1"
        type: choice
        options:
          - 5.4.1_5.10.1
          - 5.15.1_6.1.1
          - 5.4.1
          - 5.10.1
          - 5.15.1
          - 6.1.1
      auto_kernel:
        description: "Auto use the latest kernel"
        required: false
        default: true
        type: boolean
      kernel_repo:
        description: "Set the kernel repository"
        required: false
        default: "ophub/kernel"
        type: choice
        options:
          - ophub/kernel
      kernel_usage:
        description: "Set the tags of the stable kernel."
        required: false
        default: "stable"
        type: choice
        options:
          - stable
          - flippy
          - dev
          - beta
      tunnel:
        description: "Select VPN Client app (!passwall only support for newer branch with fw4 firewall!):"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - openclash
          - passwall
          - openclash-passwall
          - no-tunnel
      clean:
        description: "Do 'make clean' for each run"
        required: false
        default: "true"
        type: boolean
      upload-prerelease:
        description: "Upload as pre-release"
        required: false
        default: "false"
        type: boolean

env:
  TARGET: ${{ inputs.target }}
  RELEASE_BRANCH: ${{ inputs.release_branch }}
  ROOTFS_SIZE: ${{ inputs.rootfs}}
  TUNNEL: ${{ inputs.tunnel }}
  LOGIN_PASSWORD: friwrt
  WIFI_SSID: friWrt_5g
  WIFI_PASSWORD: friwrt2023
  CLEAN: ${{ inputs.clean }}
  TZ: Asia/Jakarta

jobs:
  Generate:
    name: ${{ inputs.release_branch }}-${{ inputs.tunnel }}
    runs-on: ubuntu-latest

    steps:
      - name: Initialization System Environment
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip tar gzip qemu-utils mkisofs
          sudo timedatectl set-timezone "$TZ"

      - name: Setup Environment Variables
        run: |
          if [ "$RELEASE_BRANCH" == "openwrt:23.05.2" ]; then
            echo "PROFILE=" >> $GITHUB_ENV
            echo "TARGET_SYSTEM=armsr/armv8" >> $GITHUB_ENV
            echo "TARGET_NAME=armsr-armv8" >> $GITHUB_ENV
            echo "ARCH_1=armv8" >> $GITHUB_ENV
            echo "ARCH_2=arm" >> $GITHUB_ENV
            echo "ARCH_3=" >> $GITHUB_ENV
          elif [ "$RELEASE_BRANCH" == "immortalwrt:23.05.1" ]; then
            echo "PROFILE=" >> $GITHUB_ENV
            echo "TARGET_SYSTEM=armsr/armv8" >> $GITHUB_ENV
            echo "TARGET_NAME=armsr-armv8" >> $GITHUB_ENV
            echo "ARCH_1=armv8" >> $GITHUB_ENV
            echo "ARCH_2=arm" >> $GITHUB_ENV
            echo "ARCH_3=" >> $GITHUB_ENV
          else
            echo "PROFILE=Default" >> $GITHUB_ENV
            echo "TARGET_SYSTEM=armvirt/64" >> $GITHUB_ENV
            echo "TARGET_NAME=armvirt-64" >> $GITHUB_ENV
            echo "ARCH_1=armvirt" >> $GITHUB_ENV
            echo "ARCH_2=armvirt" >> $GITHUB_ENV
            echo "ARCH_3=" >> $GITHUB_ENV
          fi

          echo "WORKING_DIR="${RELEASE_BRANCH%:*}"-imagebuilder-"$TARGET_NAME".Linux-x86_64" >> $GITHUB_ENV
          echo "DOWNLOAD_BASE=https://downloads."${RELEASE_BRANCH%:*}".org" >> $GITHUB_ENV
          echo "BASE=${RELEASE_BRANCH%:*}" >> $GITHUB_ENV
          echo "BRANCH=${RELEASE_BRANCH#*:}" >> $GITHUB_ENV
          echo "tags=$( [[ "${RELEASE_BRANCH#*:}" == "21.02.7" ]] && echo "21.02" )" >> $GITHUB_ENV
          echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "DATETIME=$(date +'%Y.%m.%d-%H:%M:%S')" >> $GITHUB_ENV
          echo "DATEMONTH=$(date +"%B-%Y" | awk '{print tolower($0)}')" >> $GITHUB_ENV
      
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          path: origin

      - name: Download Image Builder
        id: download
        run: |
          RELEASE="$DOWNLOAD_BASE/releases/$BRANCH/targets/$TARGET_SYSTEM/$BASE-imagebuilder-$BRANCH-$TARGET_NAME.Linux-x86_64.tar.xz"
          wget -nv "$RELEASE"
          tar -xJf *-imagebuilder-* && sync && rm -f *-imagebuilder-*.tar.xz && mv *-imagebuilder-* $WORKING_DIR && sync
          cp -r $GITHUB_WORKSPACE/origin/* $GITHUB_WORKSPACE/$WORKING_DIR
          echo "status=success" >> $GITHUB_OUTPUT
      
      - name: Download External Packages
        id: packages
        if: steps.download.outputs.status == 'success' && !cancelled()
        run: |
          cd $WORKING_DIR
          bash external-package-urls.sh
          if [[ "$BRANCH" == "21.02.7" ]]; then
             grep -E "^all-all|^old-$tags|^$ARCH_1-$tags|^$ARCH_1" external-package-urls.txt | awk '{print $2}' > output_url.txt
          else
             grep -E "^all-all|^all|^$ARCH_1" external-package-urls.txt | grep -vE "^$ARCH_1-$tags" | awk '{print $2}' > output_url.txt
          fi
          wget --no-check-certificate -i output_url.txt -nv -P packages
          echo "status=success" >> $GITHUB_OUTPUT
         
      - name: Run Patch and DIY Scripts
        id: scripts
        if: steps.packages.outputs.status == 'success' && !cancelled()
        run: |
          cd $WORKING_DIR
          bash scripts/builder-patch.sh
          bash scripts/agh-core.sh
          bash scripts/misc.sh
          if [[ "$TUNNEL" == "all" && "$BRANCH" != "21.02.7" ]]; then 
              echo "VPN Client: $TUNNEL"
              bash scripts/tunnel_app.sh openclash-passwall
          elif [[ ("$TUNNEL" == "passwall" || "$TUNNEL" == "openclash-passwall") && "$BRANCH" != "21.02.7" || "$TUNNEL" == "openclash" ]]; then
              echo "VPN Client: $TUNNEL"
              bash scripts/tunnel_app.sh "$TUNNEL"
          elif [[ "$TUNNEL" == "all" && "$BRANCH" = "21.02.7" ]]; then 
              echo "VPN Client: $TUNNEL"
              bash scripts/tunnel_app.sh openclash
          else
              echo "No VPN Client selected"
          fi
          if [ "$TUNNEL" = "openclash" ] || [ "$TUNNEL" = "openclash-passwall" ] || [ "$TUNNEL" = "all" ]; then bash scripts/clash-core.sh; fi
          ls packages
          echo "status=success" >> $GITHUB_OUTPUT
          echo -e "Server space usage before starting to compile: \n$(df -hT ${PWD}) \n"

      - name: Compile Firmware
        id: compile
        if: steps.scripts.outputs.status == 'success' && !cancelled()
        run: |
          cd $WORKING_DIR
          mkdir -p compiled_images
          if [[ "$TUNNEL" == "all" && "$BRANCH" != "21.02.7" ]]; then
            for t in openclash-passwall openclash passwall no-tunnel; do
              echo "Compiling with VPN Client: $t"
              if [ "$CLEAN" == "true" ]; echo "Start 'make clean' before building images."; then make clean; fi
              time bash make-build.sh $PROFILE $t
              for file in bin/targets/"$TARGET_SYSTEM"/*rootfs.tar.gz; do mv "$file" compiled_images; done
            done
          elif [[ "$TUNNEL" == "all" && "$BRANCH" = "21.02.7" ]]; then
            for t in openclash no-tunnel; do
              echo "Compiling with VPN Client: $t"
              if [ "$CLEAN" == "true" ]; echo "Start 'make clean' before building images."; then make clean; fi
              time bash make-build.sh $PROFILE $t
              for file in bin/targets/"$TARGET_SYSTEM"/*rootfs.tar.gz; do mv "$file" compiled_images; done
            done
          elif [[ ("$TUNNEL" == "passwall" || "$TUNNEL" == "openclash-passwall") && "$BRANCH" != "21.02.7" || "$TUNNEL" == "openclash" || "$TUNNEL" == "no-tunnel" ]]; then
            echo "Compiling with VPN Client: $TUNNEL"
            bash make-build.sh $PROFILE $TUNNEL
            for file in bin/targets/"$TARGET_SYSTEM"/*rootfs.tar.gz; do mv "$file" compiled_images; done
          fi
          ls -l compiled_images
          echo "status=success" >> $GITHUB_OUTPUT
          echo -e "Server space usage after compilation: \n$(df -hT ${PWD}) \n"

      - name: Clear server space
        if: ${{ steps.imagebuilder.outputs.status }} == 'success' && !cancelled()
        run: |
          cd $WORKING_DIR
          rm -rf $(ls . | grep -v "^compiled_images$" | xargs) 2>/dev/null
          df -hT ${PWD}

      - name: Packaging OpenWrt
        if: ${{ steps.imagebuilder.outputs.status }} == 'success' && !cancelled()
        uses: ophub/amlogic-s9xxx-openwrt@main
        with:
          openwrt_path: $WORKING_DIR/compiled_images/*rootfs.tar.gz
          openwrt_board: ${{ inputs.openwrt_board }}
          openwrt_kernel: ${{ inputs.openwrt_kernel }}
          auto_kernel: ${{ inputs.auto_kernel }}
          kernel_repo: ${{ inputs.kernel_repo }}
          kernel_usage: ${{ inputs.kernel_usage }}
          builder_name: ${{ inputs.builder_name }}

      - name: Prepare file before upload
        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
        id: prep_upload
        run: |
          cd $WORKING_DIR
          for file in ${{ env.PACKAGED_OUTPUTPATH }}/*.img.gz; do mv "$file" fri_$(basename "$file" .img.gz)$( echo "_$t" ).img.gz; done
          rm -rm *.sha && sha256sum ${{ env.PACKAGED_OUTPUTPATH }}/*.img.gz > ${{ env.PACKAGED_OUTPUTPATH }}/sha256sums
          ls -l ${{ env.PACKAGED_OUTPUTPATH }}
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Add changelog info to new release description
        if: github.event.inputs.upload-artifacts == 'false'
        id: read_release
        shell: bash
        run: |
          cd $WORKING_DIR
          r=$(awk '/^\*\*Changelog\*\*/ {if(found) exit; found=1} found' changelog_amlogic.md)
          r="${r//'%'/'%25'}"
          r="${r//$'\n'/'%0A'}"
          r="${r//$'\r'/'%0D'}"  
          echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT

      - name: Upload Firmware to Release
        uses: svenstaro/upload-release-action@v2
        if: ${{ steps.prep_upload.outputs.status }} == 'success' && !cancelled()
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ${{ env.PACKAGED_OUTPUTPATH }}/*
          asset_name: ${{ github.event.repository.name }}-${{ github.sha }}
          tag: Amlogic-${{ env.BASE }}-${{ env.BRANCH }}-${{ env.DATEMONTH }}
          overwrite: true
          prerelease: ${{ env.PRE_RELEASE }}
          body: |
            ### friWrt ${{ env.BASE }}-${{ env.BRANCH }} Image information
            Build date: ${{ env.DATETIME }}
            
            ${{ steps.read_release.outputs.RELEASE_BODY }}
            
            See [here](https://github.com/frizkyiman/friWrt-MyWrtBuilder?tab=readme-ov-file#firmware-details) for more detail feature and other information.
            - Default IP: 192.168.1.1
            - Default username: root
            - Default password: friwrt
            - Default WIFI name: friWrt_2g | friWrt_5g (if device supported)
            - Default WIFI password: friwrt2023 (if device supported)
            ### Install to EMMC
            - Login to OpenWrt → System → Amlogic Service → Install OpenWrt
